# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad26778c22e047f6b8ffbedd3c8d81b754dc28ed20f2381ca5d1096640ba9f57bc35dcb4b9f4804aef08484bde1cfa50c9720551b2d8009a8fad5cc4ed350e1

test:
  secret_key_base: 0d29352801ba02c8d211d90d3118fa2d26a3a175d9f0be5279344e6a9fc0e639a1a80a578389d380050d5341e922883914457c52882190e93a1540d50e2a9b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
